pipeline {
    agent any

    tools{
        nodejs 'node24'
    }

    stages {
        stage('Build') {
            steps {
                // Commandes pour construire l'application, par exemple avec Maven
                sh 'node -v'
            }
        }
    }
}