pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Test - Dev Environment') {
            when {
                environment name: 'DEPLOY_TO', value: 'development'
            }
            steps {
                echo 'Testing in dev environment...'
            }
        }
        stage('Test - Prod Environment') {
            when {
                allOf {
                    environment name: 'DEPLOY_TO', value: 'production'
                    expression { return params.INCLUDE_PROD_TESTS }
                }
            }
            steps {
                echo 'Testing in prod environment...'
            }
        }
        stage('Deploy') {
            when {
                not {
                    triggeredBy cause: "UserIdCause", detail: "jdoe"
                }
            }
            steps {
                echo 'Deploying...'
            }
        }
    }
}